#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"

deploy-prod:
  stage: deploy
  image: ubuntu:latest
  script:
    - apt update
    - apt install sshpass -y
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - sshpass -p zaq1234 ssh artem@cp.c025prts.one -p 55022
    - ls
  only:
    - main