#
deploy-prod:
  stage: deploy
  image: ubuntu:latest
  environment: production
  services:
    - docker:dind

  script:
    - pip3 install docker-compose
    - docker-compose up --build -d
  only:
    - main


deploy-test:
  stage: deploy
  environment: test
  image: ubuntu:latest
  services:
    - docker:dind

  script:
    - pip3 install docker-compose
    - docker-compose up --build -d
  only:
    - develop

