# Generated by Django 3.2.3 on 2021-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210601_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год урожая'),
        ),
    ]
