# Generated by Django 3.2.3 on 2021-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210604_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='warehouses',
            field=models.ManyToManyField(blank=True, to='backend.Warehouse'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
    ]
