# Generated by Django 3.2.3 on 2021-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210615_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='amount_of_NDS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер НДС'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_of_contract',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_of_spec',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания спецификации'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания экспорта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_of_contract',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_of_spec',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала спецификации'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта экспорта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='name_of_contract',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='number_of_spec',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер спецификации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%H/%M/%S', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sign_file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%H/%M/%S', verbose_name='Файл подписи'),
        ),
    ]
