# Generated by Django 3.2.3 on 2021-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210616_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_provider', models.CharField(max_length=250, verbose_name='Название компании')),
                ('head_of_provider', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО руководителя компании')),
                ('short_fio', models.CharField(blank=True, max_length=250, null=True, verbose_name='сокращенное ФИО руководителя компании')),
                ('position_head_of_provider', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('basis_of_doc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('address_load', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('ul_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Юридический адрес компании')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН компании')),
                ('kpp', models.IntegerField(blank=True, null=True, verbose_name='КПП компании')),
                ('ogrn', models.IntegerField(blank=True, null=True, verbose_name='ОГРН компании')),
                ('bik', models.IntegerField(blank=True, null=True, verbose_name='БИК компании')),
                ('payment_account', models.IntegerField(blank=True, null=True, verbose_name='Расчетный счет компании')),
                ('correspondent_account', models.IntegerField(blank=True, null=True, verbose_name='Корреспондентский счет компании')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефонный номер компании')),
                ('email_of_head', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email руководителя')),
                ('name_of_bank', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название банка')),
            ],
        ),
    ]
