# Generated by Django 3.2.3 on 2021-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_company_bik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_lifetime',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='period_of_export',
        ),
        migrations.AddField(
            model_name='offer',
            name='cots',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_finish_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания поставки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_start_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта поставки'),
        ),
    ]
