# Generated by Django 3.2.3 on 2021-06-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210622_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='cots',
            new_name='cost',
        ),
    ]
