# Generated by Django 3.2.3 on 2021-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210623_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
    ]
