# Generated by Django 3.2.3 on 2021-06-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип урожая'),
        ),
        migrations.AddField(
            model_name='product',
            name='harvest_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год урожая'),
        ),
    ]
