# Generated by Django 3.2.3 on 2021-06-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20210624_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='warehouses',
            new_name='warehouse',
        ),
    ]
