log:
  level: DEBUG
entryPoints:
  web:
    address: :{{ env.Getenv "TRAEFIK_PORT"}}
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
    transport:
      respondingtimeouts:
        idletimeout: 1800

  websecure:
    address: ":443"
    transport:
      respondingtimeouts:
        idletimeout: 1800

providers:
  docker:
    network: web

certificatesResolvers:
  tlsresolver:
    acme:
      email: a.arkhipov@skipp.pro
      storage: /etc/traefik/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
