# Generated by Django 3.2.4 on 2021-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='default',
        ),
        migrations.AddField(
            model_name='specificationsofproduct',
            name='spec',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.IntegerField(verbose_name='Цена покупателя'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Заголовок'),
        ),
    ]
