# Generated by Django 3.2.3 on 2021-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210604_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wet_gluten',
        ),
        migrations.AddField(
            model_name='product',
            name='acid_number_of_the_oil',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кислотное число масла'),
        ),
        migrations.AddField(
            model_name='product',
            name='aflatoxin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Афлатоксин'),
        ),
        migrations.AddField(
            model_name='product',
            name='alveographic_characteristics_of_the_test',
            field=models.IntegerField(blank=True, null=True, verbose_name='Альвеографические характеристики теста'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount_of_gluten',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество клейковины'),
        ),
        migrations.AddField(
            model_name='product',
            name='broken',
            field=models.IntegerField(blank=True, null=True, verbose_name='Битые'),
        ),
        migrations.AddField(
            model_name='product',
            name='colored',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цветные'),
        ),
        migrations.AddField(
            model_name='product',
            name='damage_bedbug_turtle',
            field=models.IntegerField(blank=True, null=True, verbose_name='Повреждение клопом черепашкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='damaged',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поврежденные'),
        ),
        migrations.AddField(
            model_name='product',
            name='damaged_by_drying',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поврежденные сушкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='damaged_by_mold',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поврежденные плесенью'),
        ),
        migrations.AddField(
            model_name='product',
            name='damaged_by_pests',
            field=models.IntegerField(blank=True, null=True, verbose_name='Поврежденные вредителями'),
        ),
        migrations.AddField(
            model_name='product',
            name='dirty_chickpeas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Грязный нут'),
        ),
        migrations.AddField(
            model_name='product',
            name='drop_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Число падения'),
        ),
        migrations.AddField(
            model_name='product',
            name='erucic_acid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Эруковая кислота'),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Клетчатка'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_fatty_acids',
            field=models.IntegerField(blank=True, null=True, verbose_name='Свободные жирные кислоты'),
        ),
        migrations.AddField(
            model_name='product',
            name='fumonisin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Фумонизин'),
        ),
        migrations.AddField(
            model_name='product',
            name='genetically_modified_organism',
            field=models.IntegerField(blank=True, null=True, verbose_name='Генетически модифицированный организм'),
        ),
        migrations.AddField(
            model_name='product',
            name='glucosinolates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глюкозинолаты'),
        ),
        migrations.AddField(
            model_name='product',
            name='gluten_strain_gauge',
            field=models.IntegerField(blank=True, null=True, verbose_name='Измеритель деформации клейковины'),
        ),
        migrations.AddField(
            model_name='product',
            name='grain_impurity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зерновая примесь'),
        ),
        migrations.AddField(
            model_name='product',
            name='harmful_substances',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вредные вещества'),
        ),
        migrations.AddField(
            model_name='product',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Влажность'),
        ),
        migrations.AddField(
            model_name='product',
            name='infection_is_not_allowed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Зараженность не допускается'),
        ),
        migrations.AddField(
            model_name='product',
            name='ochratoxin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Охратоксин'),
        ),
        migrations.AddField(
            model_name='product',
            name='oil_content',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масличность'),
        ),
        migrations.AddField(
            model_name='product',
            name='oilseed_admixture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Масличная примесь'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_cereals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Прочие зерновые'),
        ),
        migrations.AddField(
            model_name='product',
            name='passing_through_the_sieve',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проход через сито'),
        ),
        migrations.AddField(
            model_name='product',
            name='pesticides',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пестициды'),
        ),
        migrations.AddField(
            model_name='product',
            name='potassium_hydroxide',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гидрооксид калия'),
        ),
        migrations.AddField(
            model_name='product',
            name='protein',
            field=models.IntegerField(blank=True, null=True, verbose_name='Протеин'),
        ),
        migrations.AddField(
            model_name='product',
            name='salmonella',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сальмонелла'),
        ),
        migrations.AddField(
            model_name='product',
            name='smell',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запах'),
        ),
        migrations.AddField(
            model_name='product',
            name='trypsin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Трипсин'),
        ),
        migrations.AddField(
            model_name='product',
            name='urea',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мочевина'),
        ),
        migrations.AddField(
            model_name='product',
            name='vomitoxin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вомитоксин'),
        ),
        migrations.AddField(
            model_name='product',
            name='zearalenon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зеараленон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Натура'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weed_admixture',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сорная примесь'),
        ),
    ]
