# Generated by Django 3.2.4 on 2021-07-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_warehouse_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousedistance',
            old_name='form',
            new_name='start',
        ),
    ]
