# Generated by Django 3.2.4 on 2021-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_warehouse_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('act', 'Акт'), ('other', 'Прочее')], default='other', max_length=250, verbose_name='Тип документа'),
        ),
    ]
