# Generated by Django 3.2.4 on 2021-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_form_warehousedistance_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_for_cost',
            field=models.IntegerField(default=0, help_text='Цена за транспорт без НДС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_of_NDS',
            field=models.IntegerField(default=13, verbose_name='Размер НДС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_cost',
            field=models.IntegerField(default=0, verbose_name='Цена покупателя без НДС'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Cделка без НДС'),
        ),
    ]
