# Generated by Django 3.2.4 on 2021-07-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210720_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_for_cost',
            new_name='price_for_delivery',
        ),
    ]
