# Generated by Django 3.2.4 on 2021-06-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20210604_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_provider', models.CharField(max_length=250, verbose_name='Название компании')),
                ('head_of_provider', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО руководителя компании')),
                ('short_fio', models.CharField(blank=True, max_length=250, null=True, verbose_name='сокращенное ФИО руководителя компании')),
                ('position_head_of_provider', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('basis_of_doc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('address_load', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность руководителя компании')),
                ('ul_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Юридический адрес компании')),
                ('inn', models.IntegerField(blank=True, null=True, verbose_name='ИНН компании')),
                ('kpp', models.IntegerField(blank=True, null=True, verbose_name='КПП компании')),
                ('ogrn', models.IntegerField(blank=True, null=True, verbose_name='ОГРН компании')),
                ('bik', models.CharField(blank=True, max_length=250, null=True, verbose_name='БИК компании')),
                ('payment_account', models.CharField(blank=True, max_length=250, null=True, verbose_name='Расчетный счет компании')),
                ('correspondent_account', models.CharField(blank=True, max_length=250, null=True, verbose_name='Корреспондентский счет компании')),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефонный номер компании')),
                ('email_of_head', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email руководителя')),
                ('name_of_bank', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название банка')),
            ],
        ),
        migrations.CreateModel(
            name='NameOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, verbose_name='Тип поля')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurementOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250, verbose_name='Единица измерения')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_lifetime',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='period_of_export',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='warehouses',
        ),
        migrations.RemoveField(
            model_name='product',
            name='acid_number_of_the_oil',
        ),
        migrations.RemoveField(
            model_name='product',
            name='aflatoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alveographic_characteristics_of_the_test',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount_of_gluten',
        ),
        migrations.RemoveField(
            model_name='product',
            name='broken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colored',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damage_bedbug_turtle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_drying',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_mold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_pests',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dirty_chickpeas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='drop_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='erucic_acid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='free_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fumonisin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genetically_modified_organism',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glucosinolates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gluten_strain_gauge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grain_impurity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harmful_substances',
        ),
        migrations.RemoveField(
            model_name='product',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='infection_is_not_allowed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ochratoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oil_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oilseed_admixture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_cereals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='passing_through_the_sieve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pesticides',
        ),
        migrations.RemoveField(
            model_name='product',
            name='potassium_hydroxide',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salmonella',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smell',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trypsin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urea',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vitreous',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vomitoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weed_admixture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zearalenon',
        ),
        migrations.AddField(
            model_name='deal',
            name='amount_of_NDS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер НДС'),
        ),
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_of_contract',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_of_spec',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания спецификации'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_finish_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания экспорта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_of_contract',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_of_spec',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала спецификации'),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_start_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта экспорта'),
        ),
        migrations.AddField(
            model_name='deal',
            name='name_of_contract',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название договора'),
        ),
        migrations.AddField(
            model_name='deal',
            name='number_of_spec',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер спецификации'),
        ),
        migrations.AddField(
            model_name='deal',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%H/%M/%S', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='Имя документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='sign_file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%H/%M/%S', verbose_name='Файл подписи'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_doc',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='offer',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_finish_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания поставки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='date_start_shipment',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата старта поставки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано (время)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='harvest_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип урожая'),
        ),
        migrations.CreateModel(
            name='SpecificationsOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('is_edit_min_value', models.BooleanField(blank=True, null=True, verbose_name='Редактируемое минимальное значение?')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('is_edit_max_value', models.BooleanField(blank=True, null=True, verbose_name='Редактируемое максимальное значение?')),
                ('GOST', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип поля')),
                ('name_of_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_specification', to='main.nameofspecification')),
                ('type_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_field', to='main.typeofspecification')),
                ('unit_of_measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measurement', to='main.unitofmeasurementofspecification')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='specifications', to='main.SpecificationsOfProduct'),
        ),
    ]
