# Generated by Django 3.2.4 on 2021-07-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_document_type_doc'),
        ('main', '0007_rename_price_for_cost_order_price_for_delivery'),
    ]

    operations = [
    ]
