# Generated by Django 3.2.4 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210628_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='specifications', to='main.SpecificationsOfProduct'),
        ),
    ]
