# Generated by Django 3.2.3 on 2021-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210610_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sign_file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%h/%m/%s', verbose_name='Файл подписи'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/%h/%m/%s', verbose_name='Файл'),
        ),
    ]
