# Generated by Django 3.2.4 on 2021-06-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_specifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
    ]
