# Generated by Django 3.2.4 on 2021-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210629_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
        ),
    ]
