# Generated by Django 3.2.4 on 2021-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210701_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsofproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='GOST',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ГОСТ'),
        ),
    ]
