# Generated by Django 3.2.4 on 2021-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210701_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRateForDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_tonne', models.IntegerField(blank=True, null=True, verbose_name='Стоимость за 1 тонну')),
            ],
        ),
        migrations.CreateModel(
            name='CoefficientOfDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_distance', models.IntegerField(blank=True, null=True, verbose_name='Дистанция от')),
                ('max_distance', models.IntegerField(blank=True, null=True, verbose_name='Дистанция до')),
                ('coefficient', models.FloatField(blank=True, null=True, verbose_name='Коэффициент умножения')),
            ],
        ),
    ]
