# Generated by Django 3.2.4 on 2021-07-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_baseratefordelivery_coefficientofdistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расстояние'),
        ),
    ]
