# Generated by Django 3.2.4 on 2021-07-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210725_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_doc',
            field=models.CharField(choices=[('other', 'Прочее'), ('specification', 'Спецификация'), ('contract_for_signing', 'Договор на подписание'), ('payment_invoice', 'Счет на оплату'), ('quality_certificate', 'Сертификат качества'), ('contract', 'Договор'), ('payment_order', 'Платежное поручение'), ('verification_act', 'Акт сверки'), ('book_of_purchases_or_sales', 'Книга покупок/продаж'), ('letter_for_refund', 'Письмо на возврат'), ('loading_plan', 'План погрузки'), ('report_on_the_shipped_goods', 'Отчет о погруженном товаре'), ('additional_payment_invoice', 'Счет на доплату'), ('universal_transfer_document', 'Универсальный передаточный документ')], default='other', max_length=250, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tax_type',
            field=models.CharField(choices=[('simple', 'Упрощенная'), ('main', 'Основной')], default='simple', max_length=25),
        ),
    ]
