# Generated by Django 3.2.4 on 2021-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_baseratefordelivery_coefficientofdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=250, null=True, verbose_name='Статус'),
        ),
    ]
