# Generated by Django 3.2.4 on 2021-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210726_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('step1', 'step1'), ('step2_onway', 'step2_onway'), ('step2_tests_taken', 'step2_tests_taken'), ('step2_quality', 'step2_quality'), ('step2_quality_accepted', 'step2_quality_accepted'), ('step2_quality_failed', 'step2_quality_failed'), ('step3', 'step3'), ('step3_docs_ready', 'step3_docs_ready'), ('step3_sign_ready', 'step3_sign_ready'), ('step3_prebill_send', 'step3_prebill_send'), ('step4', 'step4'), ('step4_plan_ready', 'step4_plan_ready'), ('step4_selected_date', 'step4_selected_date'), ('step4_date_approved', 'step4_date_approved'), ('step4_loading_started', 'step4_loading_started'), ('step4_over_today', 'step4_over_today'), ('step4_over_contract', 'step4_over_contract'), ('step4_done', 'step4_done')], default='step1', max_length=50),
        ),
    ]
