# Generated by Django 3.2.4 on 2021-07-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_offer_status'),
        ('main', '0013_warehouse_distance'),
    ]

    operations = [
    ]
