# Generated by Django 3.2.4 on 2021-07-09 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_merge_0013_alter_offer_status_0013_warehouse_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[], max_length=50)),
                ('accepted_volume', models.IntegerField()),
                ('name_of_contract', models.CharField(default='', max_length=250, verbose_name='Название договора')),
                ('number_of_spec', models.CharField(default='', max_length=250, verbose_name='Номер спецификации')),
                ('date_start_of_spec', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала спецификации')),
                ('date_finish_of_spec', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания спецификации')),
                ('date_start_of_contract', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала договора')),
                ('date_finish_of_contract', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания договора')),
                ('date_start_shipment', models.DateTimeField(blank=True, null=True, verbose_name='Дата старта экспорта')),
                ('date_finish_shipment', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания экспорта')),
                ('amount_of_NDS', models.IntegerField(default=0, verbose_name='Размер НДС')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(to='main.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateForDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_tonne', models.IntegerField(blank=True, null=True, verbose_name='Стоимость за 1 тонну')),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('delta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BaseRateForDelivery',
        ),
        migrations.DeleteModel(
            name='CoefficientOfDistance',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='control',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='quality_control',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='carsforshipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='carsforshipment',
            name='shipment_fact',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='is_edit_max_value',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='is_edit_min_value',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='name_of_specification',
        ),
        migrations.RemoveField(
            model_name='specificationsofproduct',
            name='type_field',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='distance',
        ),
        migrations.AddField(
            model_name='carsforshipment',
            name='deliver',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationsofproduct',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationsofproduct',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specificationsofproduct',
            name='type',
            field=models.CharField(choices=[('int', 'Целочисленное'), ('range', 'Диапозон'), ('string', 'Строковое'), ('bool', 'Логическое'), ('decimal', 'Десятичное')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address_load',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Должность руководителя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='basis_of_doc',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Должность руководителя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bik',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='БИК компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='correspondent_account',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Корреспондентский счет компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_of_head',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Email руководителя'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_of_provider',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ФИО руководителя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='ИНН компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='КПП компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_of_bank',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='ОГРН компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_account',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Расчетный счет компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Телефонный номер компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='position_head_of_provider',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Должность руководителя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_fio',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='сокращенное ФИО руководителя компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ul_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Юридический адрес компании'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('archived', 'Архивирован'), ('accepted', 'Принят'), ('pending', 'В процессе'), ('partial', 'Частично выполнен')], default='active', max_length=250, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default=0, max_length=250, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='volume',
            field=models.IntegerField(default=0, verbose_name='Объем'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='specifications', to='main.SpecificationsOfProduct'),
        ),
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='unit_of_measurement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measurement', to='main.unitofmeasurementofspecification'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='NameOfSpecification',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='QualityControl',
        ),
        migrations.DeleteModel(
            name='TypeOfSpecification',
        ),
        migrations.DeleteModel(
            name='Сontrol',
        ),
        migrations.AddField(
            model_name='warehousedistance',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousedistance',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ends', to='main.warehouse'),
        ),
        migrations.AddField(
            model_name='ratefordelivery',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='main.warehousedistance'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_values', to='main.product'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_values', to='main.specificationsofproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.offer'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='categories', to='main.SpecificationsOfProduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
