# Generated by Django 3.2.3 on 2021-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_cots_offer_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationsOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_specification', models.CharField(max_length=250, verbose_name='Название характеристики')),
                ('type_field', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип поля')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=250, null=True, verbose_name='Единица измерения')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Минимальное значение')),
                ('is_edit_min_value', models.BooleanField(blank=True, null=True, verbose_name='Редактируемое минимальное значение?')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Максимальное значение')),
                ('is_edit_max_value', models.BooleanField(blank=True, null=True, verbose_name='Редактируемое максимальное значение?')),
                ('GOST', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип поля')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='acid_number_of_the_oil',
        ),
        migrations.RemoveField(
            model_name='product',
            name='aflatoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alveographic_characteristics_of_the_test',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount_of_gluten',
        ),
        migrations.RemoveField(
            model_name='product',
            name='broken',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colored',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damage_bedbug_turtle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_drying',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_mold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='damaged_by_pests',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dirty_chickpeas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='drop_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='erucic_acid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='free_fatty_acids',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fumonisin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genetically_modified_organism',
        ),
        migrations.RemoveField(
            model_name='product',
            name='glucosinolates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gluten_strain_gauge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grain_impurity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harmful_substances',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_year',
        ),
        migrations.RemoveField(
            model_name='product',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='infection_is_not_allowed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moisture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ochratoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oil_content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='oilseed_admixture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_cereals',
        ),
        migrations.RemoveField(
            model_name='product',
            name='passing_through_the_sieve',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pesticides',
        ),
        migrations.RemoveField(
            model_name='product',
            name='potassium_hydroxide',
        ),
        migrations.RemoveField(
            model_name='product',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salmonella',
        ),
        migrations.RemoveField(
            model_name='product',
            name='smell',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trypsin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='urea',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vitreous',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vomitoxin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weed_admixture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='zearalenon',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='backend.SpecificationsOfProduct'),
        ),
    ]
