# Generated by Django 3.2.4 on 2021-07-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210709_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый')], default='new', max_length=50),
        ),
    ]
