# Generated by Django 3.2.3 on 2021-06-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250, verbose_name='Тип поля')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurementOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=250, verbose_name='Единица измерения')),
            ],
        ),
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='name_of_specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_specification', to='backend.nameofspecification'),
        ),
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='type_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_field', to='backend.typeofspecification'),
        ),
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='unit_of_measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_measurement', to='backend.unitofmeasurementofspecification'),
        ),
    ]
