# Generated by Django 3.2.4 on 2021-07-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin', 'Админ'), ('farmer', 'Фермер'), ('provider', 'Провайдер')], default='farmer', max_length=25),
        ),
    ]
