# Generated by Django 3.2.4 on 2021-07-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tax_type',
            field=models.CharField(choices=[('simple', 'Упрощенная')], default='simple', max_length=25),
        ),
    ]
