# Generated by Django 3.2.4 on 2021-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_offer_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
