# Generated by Django 3.2.4 on 2021-07-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_offer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
