# Generated by Django 3.2.3 on 2021-06-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_warehouses_offer_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationsofproduct',
            name='name_of_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_of_specification', to='backend.nameofspecification'),
        ),
    ]
