# Generated by Django 3.2.4 on 2021-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='documents',
            field=models.ManyToManyField(blank=True, to='main.Document'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_of_contract',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Название договора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_spec',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Номер спецификации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='specifications', through='main.ProductSpecification', to='main.SpecificationsOfProduct'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('admin', 'Админ'), ('customer', 'Фермер'), ('crm', 'Провайдер')], default='customer', max_length=25),
        ),
    ]
