# Generated by Django 3.2.4 on 2021-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationsofproduct',
            name='default',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
